### PR TITLE
Initial quordlepleen

### PR DESCRIPTION
**Pull request by ifosch**

### CODE REVIEW

**Comment by towanda** [comment]
+1

**Comment by christofdamian** [comment]
( ( ( ( +1 ) ) ) )

**Comment by towanda** [comment]
LOL

**Comment by jezuhke** [comment]
+1

**Comment by yaneq** [comment]
+1 :joy: 

.. whats `quordlepleen`?

**Comment by ifosch** [comment]
@yaneq http://hitchhikers.wikia.com/wiki/Max_Quordlepleen

**Comment by yaneq** [comment]
(:+1:)

**Pull request merged**
