### PR TITLE
Idea Proposal: Toolbox Editor

### PR DESCRIPTION
**Pull request by yaneq**

### CODE REVIEW

**Comment by dsager** [comment]
+1
interesting!

**Comment by yaneq** [comment]
closing this for now, since hackathon is over

**Comment by dsager** [comment]
like i said in another PR, i don't think these ideas have to be related to a hackathon. we might even tackle them sometime in a normal sprint. not sure though, if this is the right place to collect them though... I'd say yes.

**Comment by yaneq** [comment]
maybe someone can +1 this as well to get it into the repo and close the PR

**Comment by yaneq** [comment]
ok, i see noone is reading this. closing for good

**Pull request closed without merging**
