### PR TITLE
Idea Proposal: Match Employments to Jobs

### PR DESCRIPTION
**Pull request by dsager**

### CODE REVIEW

**Comment by ifosch** [comment]
+1

**Comment by yaneq** [comment]
this is probably mostly a manual task

**Comment by dsager** [comment]
Yes, it won't work without manual confirmation. Before there's a lot of filtering to be done in order to get a list of possible matches...
I still think that this would be an interesting data set to work on and could yield some valuable insights.

**Comment by nicolas-fricke** [comment]
While I think that it'd be super valuable to have these matches, I don't see how this can be achieved in a hackathon.. Also, for this to yield good results we probably first should consolidate our company table – currently we have multiple entries per company.

**Comment by dsager** [comment]
@nicolas-fricke the ideas don't have to necessarily be doable in a hackathon. It's more about general topics that should be investigated. For example in the upcoming hackathon we could work with some simple samples and try different algorithms. When the results look promising, we can then continue later on during normal sprints or another hackathon...

**Comment by yaneq** [comment]
+1

**Pull request merged**
